### PR TITLE
Bootstrap 4 beta

### PR DESCRIPTION
**Pull request by dangerousbeans**
screen shot 2017-10-22 at 7 45 37 pm

### CODE REVIEW

**Comment by evbogue** [comment]
@dangerousbeans I want to do my best to facilitate this theme without merging it directly into master. I'm partial to the bootstrap 2 buttons at the moment, even though they are a bit retro. 

Let's discuss how to best theme Decent in downstream clients?

**Comment by dangerousbeans** [comment]
I don't really mind which framework version we map to, but I feel there's some power in mapping to at least one (this PR removes all app specific css)

One of the big changes is aligning `messages` to match the structure of the media object: https://getbootstrap.com/2.3.2/components.html#media

We could also bring the old button style into the newer framework?

**Comment by dangerousbeans** [comment]
Maybe there's a vanilla, boring base version of the app, and peoples instances are forks of it?

**Comment by evbogue** [comment]
I'm thinking about the best way to do this. 

I looked into the media object from bootstrap 2, and I think it's a little different from what is going on in the decent client because decent (and really all of the clients that originally were built off patchbay) use Flexbox as the overarching layout strategy. 

Flexbox is great, but it does weird things such as disabling floats.

**Comment by evbogue** [comment]
hey @dangerousbeans. I'm going to close this pull request. 

I'm hoping that the work going into http://github.com/dominictarr/patchless and thus http://github.com/evbogue/minbay will help make it easier for us to build custom views in the next big release of Decent.

**Pull request closed without merging**
